In [1]:
import pandas as pd

In [2]:
csv_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(csv_url)

In [3]:
print('hi')

hi

In [4]:
#  slice the dataframe from 'school' until the 'guardian' column
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [6]:
df.loc[:,'school':'guardian']

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

In [7]:
# Create a lambda function that will capitalize strings.
capital_str = lambda x : x.capitalize()

In [9]:
# Capitalize both Mjob and Fjob
df['Fjob'] = df['Fjob'].apply(capital_str)
df['Mjob'] = df['Mjob'].apply(capital_str)

In [11]:
# Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)
df['age'].dtype
majority = lambda a : a > 17

In [12]:
df['legal_drinker'] = df['age'].apply(majority)

In [13]:
df['legal_drinker'].head(4)

0     True
1    False
2    False
3    False
Name: legal_drinker, dtype: bool

In [14]:
# Multiply every number of the dataset by 10
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 34 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   school         395 non-null    str
 1   sex            395 non-null    str
 2   age            395 non-null    int64
 3   address        395 non-null    str
 4   famsize        395 non-null    str
 5   Pstatus        395 non-null    str
 6   Medu           395 non-null    int64
 7   Fedu           395 non-null    int64
 8   Mjob           395 non-null    str
 9   Fjob           395 non-null    str
 10  reason         395 non-null    str
 11  guardian       395 non-null    str
 12  traveltime     395 non-null    int64
 13  studytime      395 non-null    int64
 14  failures       395 non-null    int64
 15  schoolsup      395 non-null    str
 16  famsup         395 non-null    str
 17  paid           395 non-null    str
 18  activities     395 non-null    str
 19  nursery        395 non-null    str
 20  higher         395 non-null    str
 21  internet       395 non-null    str
 22  romantic       395 non-null    str
 23  famrel         395 non-null    int64
 24  freetime       395 non-null    int64
 25  goout          395 non-null    int64
 26  Dalc           395 non-null    int64
 27  Walc           395 non-null    int64
 28  health         395 non-null    int64
 29  absences       395 non-null    int64
 30  G1             395 non-null    int64
 31  G2             395 non-null    int64
 32  G3             395 non-null    int64
 33  legal_drinker  395 non-null    bool
dtypes: bool(1), int64(16), str(17)
memory usage: 102.4 KB

In [23]:
def times_10(x):
    if isinstance(x, int):
        return 10*x 
    return x

In [25]:
df.map(times_10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,10
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,0
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,0
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,0
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,...,50,40,40,50,40,110,90,90,90,10
391,MS,M,170,U,LE3,T,30,10,Services,Services,...,40,50,30,40,20,30,140,160,160,0
392,MS,M,210,R,GT3,T,10,10,Other,Other,...,50,30,30,30,30,30,100,80,70,10
393,MS,M,180,R,LE3,T,30,20,Services,Other,...,40,10,30,40,50,0,110,120,100,10
394,MS,M,190,U,LE3,T,10,10,Other,At_home,...,20,30,30,30,50,50,80,90,90,10

In [ ]:
## imp que -> why is apply slow and vectorization is fased 
# Because it executes Python-level function calls per element/row instead of leveraging NumPy’s vectorized C-level operations.
# vectorlized -> df = df * 10